repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--profile', 'black']
  - repo: https://github.com/darkslab/pre-commit-pyre-check
    rev: 'v3.0.0-0.9.10' # pre-commit-pyre-check (v3.0.0) and pyre-check (0.9.10)
    hooks:
      - id: pyre-check
        additional_dependencies:
          - aiohttp==3.8.1
          - yarl==1.7.2
